apiVersion: v1
kind: ConfigMap
metadata:
  name: aspire-these-nutz-config
data:
  ASPNETCORE_URLS: "https://+:8443;http://+:8080"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/tls/tls.crt"
  ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/tls/tls.key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://aspire-dashboard:18889"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  DOTNET_RESOURCE_SERVICE_ENDPOINT_URL: "https://aspire-dashboard:18892"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  DEPLOYMENT_ENVIRONMENT: "Kubernetes"
  API_BASE_URL: "https://aspire-deez-nuts-api:8443"
  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: "false"
  Authentication__TokenRefreshIntervalMinutes: "5"
  services__aspire-deez-nuts-api__http__0: "http://aspire-deez-nuts-api:8080"
  services__aspire-deez-nuts-api__https__0: "https://aspire-deez-nuts-api:8443"
  services__aspire-deez-nuts-web__http__0: "http://aspire-deez-nuts-web:8080"
  services__aspire-deez-nuts-web__https__0: "https://aspire-deez-nuts-web:8443"
  services__aspire-deez-nuts-fuzz__http__0: "http://aspire-deez-nuts-fuzz:8080"
  services__aspire-deez-nuts-fuzz__https__0: "https://aspire-deez-nuts-fuzz:8443"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aspire-api-config
data:
  ASPNETCORE_URLS: "https://+:8443;http://+:8080"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/tls/tls.crt"
  ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/tls/tls.key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://aspire-dashboard:18889"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  DOTNET_RESOURCE_SERVICE_ENDPOINT_URL: "https://aspire-dashboard:18892"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  DEPLOYMENT_ENVIRONMENT: "Kubernetes"
  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: "false"
  UseInMemoryDatabase: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aspire-dashboard-config
data:
  ASPNETCORE_URLS: "https://+:18443;http://+:18888"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/tls/tls.crt"
  ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/tls/tls.key"
  DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: "https://+:18889"
  DOTNET_DASHBOARD_OTLP_HTTP_ENDPOINT_URL: "https://+:18890"
  DASHBOARD__RESOURCESERVICE__ENDPOINT: "https://+:18892"
  ASPNETCORE_DATAPROTECTION_APPLICATIONNAME: "aspire-dashboard"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aspire-fuzz-config
data:
  ASPNETCORE_URLS: "https://+:8443;http://+:8080"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/tls/tls.crt"
  ASPNETCORE_Kestrel__Certificates__Default__KeyPath: "/tls/tls.key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "https://aspire-dashboard:18889"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  DOTNET_RESOURCE_SERVICE_ENDPOINT_URL: "https://aspire-dashboard:18892"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  DEPLOYMENT_ENVIRONMENT: "Kubernetes"
  DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER: "false"
  services__aspire-deez-nuts-api__http__0: "http://aspire-deez-nuts-api:8080"
  services__aspire-deez-nuts-api__https__0: "https://aspire-deez-nuts-api:8443"