apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - jwt-secret.yaml
  - admin-seed-secret.yaml
  - configmap.yaml
  - pvc.yaml
  - cert-manager-issuer.yaml
  - certificates.yaml
  - dashboard.yaml
  - api-service.yaml
  - web-service.yaml
  - fuzz-testing-service.yaml